<?php

return [
  '0' => [
    0 => [
      '' => false,
      'var' => [0,'expression'],
      'define' => [0,'expression'],
      'true' => [0,'expression'],
      'false' => [0,'expression'],
      '1' => [0,'expression'],
      '"' => [0,'expression'],
      '\'' => [0,'expression'],
      '%' => [0,'expression'],
      '[:' => [0,'expression'],
      'pure' => [0,'expression'],
      'function' => [0,'expression'],
      '*' => [0,'expression'],
      '{' => [0,'expression'],
      'for' => [0,'expression'],
      'foreach' => [0,'expression'],
      'do' => [0,'expression'],
      'if' => [0,'expression'],
      'case' => [0,'expression'],
      '@' => [0,'expression'],
      '$' => [0,'expression'],
      'and' => [0,'expression'],
      'or' => [0,'expression'],
      'exit' => [0,'flow-control'],
      'return' => [0,'flow-control'],
    ],
  ],
  'function' => [
    0 => [
      '' => 1,
      'pure' => 1,
    ],
    1 => [
      'function' => 2,
    ],
    2 => [
      '(' => 3,
    ],
    3 => [
      '' => 4,
      '@' => [4,'arg-list'],
      '*' => [4,'arg-list'],
    ],
    4 => [
      ')' => 5,
    ],
    5 => [
      '{' => 6,
    ],
    6 => [
      '' => 7,
      'var' => [6,'expression'],
      'define' => [6,'expression'],
      'true' => [6,'expression'],
      'false' => [6,'expression'],
      '1' => [6,'expression'],
      '"' => [6,'expression'],
      '\'' => [6,'expression'],
      '%' => [6,'expression'],
      '[:' => [6,'expression'],
      'pure' => [6,'expression'],
      'function' => [6,'expression'],
      '*' => [6,'expression'],
      '{' => [6,'expression'],
      'for' => [6,'expression'],
      'foreach' => [6,'expression'],
      'do' => [6,'expression'],
      'if' => [6,'expression'],
      'case' => [6,'expression'],
      '@' => [6,'expression'],
      '$' => [6,'expression'],
      'and' => [6,'expression'],
      'or' => [6,'expression'],
      'exit' => [6,'flow-control'],
      'return' => [6,'flow-control'],
    ],
    7 => [
      '}' => false,
    ],
  ],
  'loop-if-block' => [
    0 => [
      'if' => 1,
    ],
    1 => [
      '@' => [2,'value'],
      '$' => [2,'value'],
      '*' => [2,'value'],
      'true' => [2,'value'],
      'false' => [2,'value'],
      '1' => [2,'value'],
      '"' => [2,'value'],
      '\'' => [2,'value'],
      '%' => [2,'value'],
      '[:' => [2,'value'],
      'pure' => [2,'value'],
      'function' => [2,'value'],
      '{' => [2,'value'],
      'and' => [2,'value'],
      'or' => [2,'value'],
    ],
    2 => [
      'then' => 3,
    ],
    3 => [
      'var' => [4,'loop-if-body'],
      'define' => [4,'loop-if-body'],
      'true' => [4,'loop-if-body'],
      'false' => [4,'loop-if-body'],
      '1' => [4,'loop-if-body'],
      '"' => [4,'loop-if-body'],
      '\'' => [4,'loop-if-body'],
      '%' => [4,'loop-if-body'],
      '[:' => [4,'loop-if-body'],
      'pure' => [4,'loop-if-body'],
      'function' => [4,'loop-if-body'],
      '*' => [4,'loop-if-body'],
      'for' => [4,'loop-if-body'],
      'foreach' => [4,'loop-if-body'],
      'do' => [4,'loop-if-body'],
      'if' => [4,'loop-if-body'],
      'case' => [4,'loop-if-body'],
      '@' => [4,'loop-if-body'],
      '$' => [4,'loop-if-body'],
      'continue' => [4,'loop-if-body'],
      'break' => [4,'loop-if-body'],
      'while' => [4,'loop-if-body'],
      'until' => [4,'loop-if-body'],
      '{' => [4,'loop-if-body'],
    ],
    4 => [
      '' => false,
      'else' => [false,'loop-else-case'],
    ],
  ],
  'list' => [
    0 => [
      '[:' => 1,
    ],
    1 => [
      '' => 2,
      '.' => [2,'list-body'],
      '@' => [2,'list-body'],
      '$' => [2,'list-body'],
      '*' => [2,'list-body'],
      'true' => [2,'list-body'],
      'false' => [2,'list-body'],
      '1' => [2,'list-body'],
      '"' => [2,'list-body'],
      '\'' => [2,'list-body'],
      '%' => [2,'list-body'],
      '[:' => [2,'list-body'],
      'pure' => [2,'list-body'],
      'function' => [2,'list-body'],
      '{' => [2,'list-body'],
      'and' => [2,'list-body'],
      'or' => [2,'list-body'],
      ',' => [2,'list-body'],
    ],
    2 => [
      ':]' => false,
    ],
  ],
  'call' => [
    0 => [
      '(' => 1,
    ],
    1 => [
      '' => 2,
      '.' => [2,'list-body'],
      '@' => [2,'list-body'],
      '$' => [2,'list-body'],
      '*' => [2,'list-body'],
      'true' => [2,'list-body'],
      'false' => [2,'list-body'],
      '1' => [2,'list-body'],
      '"' => [2,'list-body'],
      '\'' => [2,'list-body'],
      '%' => [2,'list-body'],
      '[:' => [2,'list-body'],
      'pure' => [2,'list-body'],
      'function' => [2,'list-body'],
      '{' => [2,'list-body'],
      'and' => [2,'list-body'],
      'or' => [2,'list-body'],
      ',' => [2,'list-body'],
    ],
    2 => [
      ')' => false,
    ],
  ],
  'arg-list' => [
    0 => [
      '@' => [1,'arg-definition'],
      '*' => [1,'arg-definition'],
    ],
    1 => [
      '' => false,
      ',' => 2,
    ],
    2 => [
      '@' => [1,'arg-definition'],
      '*' => [1,'arg-definition'],
    ],
  ],
  'variable' => [
    0 => [
      'var' => 1,
    ],
    1 => [
      '*' => [false,'variable-spec'],
      '(' => 2,
    ],
    2 => [
      '*' => [3,'variable-spec'],
    ],
    3 => [
      '' => 4,
      ',' => 5,
    ],
    4 => [
      ')' => false,
    ],
    5 => [
      '*' => [3,'variable-spec'],
    ],
  ],
  'loop-else-case' => [
    0 => [
      'else' => 1,
    ],
    1 => [
      'var' => [false,'loop-body'],
      'define' => [false,'loop-body'],
      'true' => [false,'loop-body'],
      'false' => [false,'loop-body'],
      '1' => [false,'loop-body'],
      '"' => [false,'loop-body'],
      '\'' => [false,'loop-body'],
      '%' => [false,'loop-body'],
      '[:' => [false,'loop-body'],
      'pure' => [false,'loop-body'],
      'function' => [false,'loop-body'],
      '*' => [false,'loop-body'],
      'for' => [false,'loop-body'],
      'foreach' => [false,'loop-body'],
      'do' => [false,'loop-body'],
      'if' => [false,'loop-body'],
      'case' => [false,'loop-body'],
      '@' => [false,'loop-body'],
      '$' => [false,'loop-body'],
      'continue' => [false,'loop-body'],
      'break' => [false,'loop-body'],
      'while' => [false,'loop-body'],
      'until' => [false,'loop-body'],
      '{' => [false,'loop-body'],
    ],
  ],
  'loop-if-body' => [
    0 => [
      'var' => [false,'loop-body'],
      'define' => [false,'loop-body'],
      'true' => [false,'loop-body'],
      'false' => [false,'loop-body'],
      '1' => [false,'loop-body'],
      '"' => [false,'loop-body'],
      '\'' => [false,'loop-body'],
      '%' => [false,'loop-body'],
      '[:' => [false,'loop-body'],
      'pure' => [false,'loop-body'],
      'function' => [false,'loop-body'],
      '*' => [false,'loop-body'],
      'for' => [false,'loop-body'],
      'foreach' => [false,'loop-body'],
      'do' => [false,'loop-body'],
      'if' => [false,'loop-body'],
      'case' => [false,'loop-body'],
      '@' => [false,'loop-body'],
      '$' => [false,'loop-body'],
      'continue' => [false,'loop-body'],
      'break' => [false,'loop-body'],
      'while' => [false,'loop-body'],
      'until' => [false,'loop-body'],
      '{' => [false,'loop-body'],
    ],
  ],
  'do-block' => [
    0 => [
      'do' => 1,
    ],
    1 => [
      'var' => [false,'loop-body'],
      'define' => [false,'loop-body'],
      'true' => [false,'loop-body'],
      'false' => [false,'loop-body'],
      '1' => [false,'loop-body'],
      '"' => [false,'loop-body'],
      '\'' => [false,'loop-body'],
      '%' => [false,'loop-body'],
      '[:' => [false,'loop-body'],
      'pure' => [false,'loop-body'],
      'function' => [false,'loop-body'],
      '*' => [false,'loop-body'],
      'for' => [false,'loop-body'],
      'foreach' => [false,'loop-body'],
      'do' => [false,'loop-body'],
      'if' => [false,'loop-body'],
      'case' => [false,'loop-body'],
      '@' => [false,'loop-body'],
      '$' => [false,'loop-body'],
      'continue' => [false,'loop-body'],
      'break' => [false,'loop-body'],
      'while' => [false,'loop-body'],
      'until' => [false,'loop-body'],
      '{' => [false,'loop-body'],
    ],
  ],
  'foreach-block' => [
    0 => [
      'foreach' => 1,
    ],
    1 => [
      '(' => 2,
    ],
    2 => [
      '@' => [3,'each-object'],
      '$' => [3,'each-object'],
      '*' => [3,'each-object'],
      'true' => [3,'each-object'],
      'false' => [3,'each-object'],
      '1' => [3,'each-object'],
      '"' => [3,'each-object'],
      '\'' => [3,'each-object'],
      '%' => [3,'each-object'],
      '[:' => [3,'each-object'],
      'pure' => [3,'each-object'],
      'function' => [3,'each-object'],
      '{' => [3,'each-object'],
      'and' => [3,'each-object'],
      'or' => [3,'each-object'],
    ],
    3 => [
      '' => 4,
      ',' => 5,
    ],
    4 => [
      ')' => 10,
    ],
    5 => [
      '' => 6,
      '*' => [6,'each-value'],
    ],
    6 => [
      '' => 4,
      ',' => 7,
    ],
    7 => [
      '' => 8,
      '*' => [8,'each-key'],
    ],
    8 => [
      '' => 4,
      ',' => 9,
    ],
    9 => [
      '*' => [4,'each-index'],
    ],
    10 => [
      'do' => 11,
    ],
    11 => [
      'var' => [false,'loop-body'],
      'define' => [false,'loop-body'],
      'true' => [false,'loop-body'],
      'false' => [false,'loop-body'],
      '1' => [false,'loop-body'],
      '"' => [false,'loop-body'],
      '\'' => [false,'loop-body'],
      '%' => [false,'loop-body'],
      '[:' => [false,'loop-body'],
      'pure' => [false,'loop-body'],
      'function' => [false,'loop-body'],
      '*' => [false,'loop-body'],
      'for' => [false,'loop-body'],
      'foreach' => [false,'loop-body'],
      'do' => [false,'loop-body'],
      'if' => [false,'loop-body'],
      'case' => [false,'loop-body'],
      '@' => [false,'loop-body'],
      '$' => [false,'loop-body'],
      'continue' => [false,'loop-body'],
      'break' => [false,'loop-body'],
      'while' => [false,'loop-body'],
      'until' => [false,'loop-body'],
      '{' => [false,'loop-body'],
    ],
  ],
  'for-block' => [
    0 => [
      'for' => 1,
    ],
    1 => [
      '*' => [2,'for-counter'],
    ],
    2 => [
      ':' => 3,
    ],
    3 => [
      '*' => [4,'for-start'],
      'true' => [4,'for-start'],
      'false' => [4,'for-start'],
      '1' => [4,'for-start'],
      '"' => [4,'for-start'],
      '\'' => [4,'for-start'],
      '%' => [4,'for-start'],
      '[:' => [4,'for-start'],
      'pure' => [4,'for-start'],
      'function' => [4,'for-start'],
      '{' => [4,'for-start'],
    ],
    4 => [
      'to' => 5,
    ],
    5 => [
      '*' => [6,'for-end'],
      'true' => [6,'for-end'],
      'false' => [6,'for-end'],
      '1' => [6,'for-end'],
      '"' => [6,'for-end'],
      '\'' => [6,'for-end'],
      '%' => [6,'for-end'],
      '[:' => [6,'for-end'],
      'pure' => [6,'for-end'],
      'function' => [6,'for-end'],
      '{' => [6,'for-end'],
    ],
    6 => [
      '' => 7,
      'step' => 8,
    ],
    7 => [
      'do' => 9,
    ],
    8 => [
      '*' => [7,'for-step'],
      'true' => [7,'for-step'],
      'false' => [7,'for-step'],
      '1' => [7,'for-step'],
      '"' => [7,'for-step'],
      '\'' => [7,'for-step'],
      '%' => [7,'for-step'],
      '[:' => [7,'for-step'],
      'pure' => [7,'for-step'],
      'function' => [7,'for-step'],
      '{' => [7,'for-step'],
    ],
    9 => [
      'var' => [false,'loop-body'],
      'define' => [false,'loop-body'],
      'true' => [false,'loop-body'],
      'false' => [false,'loop-body'],
      '1' => [false,'loop-body'],
      '"' => [false,'loop-body'],
      '\'' => [false,'loop-body'],
      '%' => [false,'loop-body'],
      '[:' => [false,'loop-body'],
      'pure' => [false,'loop-body'],
      'function' => [false,'loop-body'],
      '*' => [false,'loop-body'],
      'for' => [false,'loop-body'],
      'foreach' => [false,'loop-body'],
      'do' => [false,'loop-body'],
      'if' => [false,'loop-body'],
      'case' => [false,'loop-body'],
      '@' => [false,'loop-body'],
      '$' => [false,'loop-body'],
      'continue' => [false,'loop-body'],
      'break' => [false,'loop-body'],
      'while' => [false,'loop-body'],
      'until' => [false,'loop-body'],
      '{' => [false,'loop-body'],
    ],
  ],
  'when-case' => [
    0 => [
      'when' => 1,
    ],
    1 => [
      '@' => [2,'when-value'],
      '$' => [2,'when-value'],
      '*' => [2,'when-value'],
      'true' => [2,'when-value'],
      'false' => [2,'when-value'],
      '1' => [2,'when-value'],
      '"' => [2,'when-value'],
      '\'' => [2,'when-value'],
      '%' => [2,'when-value'],
      '[:' => [2,'when-value'],
      'pure' => [2,'when-value'],
      'function' => [2,'when-value'],
      '{' => [2,'when-value'],
      'and' => [2,'when-value'],
      'or' => [2,'when-value'],
      '(' => 3,
    ],
    2 => [
      'then' => 7,
    ],
    3 => [
      '@' => [4,'when-value'],
      '$' => [4,'when-value'],
      '*' => [4,'when-value'],
      'true' => [4,'when-value'],
      'false' => [4,'when-value'],
      '1' => [4,'when-value'],
      '"' => [4,'when-value'],
      '\'' => [4,'when-value'],
      '%' => [4,'when-value'],
      '[:' => [4,'when-value'],
      'pure' => [4,'when-value'],
      'function' => [4,'when-value'],
      '{' => [4,'when-value'],
      'and' => [4,'when-value'],
      'or' => [4,'when-value'],
    ],
    4 => [
      '' => 5,
      ',' => 6,
    ],
    5 => [
      ')' => 2,
    ],
    6 => [
      '@' => [4,'when-value'],
      '$' => [4,'when-value'],
      '*' => [4,'when-value'],
      'true' => [4,'when-value'],
      'false' => [4,'when-value'],
      '1' => [4,'when-value'],
      '"' => [4,'when-value'],
      '\'' => [4,'when-value'],
      '%' => [4,'when-value'],
      '[:' => [4,'when-value'],
      'pure' => [4,'when-value'],
      'function' => [4,'when-value'],
      '{' => [4,'when-value'],
      'and' => [4,'when-value'],
      'or' => [4,'when-value'],
    ],
    7 => [
      'var' => [false,'when-body'],
      'define' => [false,'when-body'],
      'true' => [false,'when-body'],
      'false' => [false,'when-body'],
      '1' => [false,'when-body'],
      '"' => [false,'when-body'],
      '\'' => [false,'when-body'],
      '%' => [false,'when-body'],
      '[:' => [false,'when-body'],
      'pure' => [false,'when-body'],
      'function' => [false,'when-body'],
      '*' => [false,'when-body'],
      '{' => [false,'when-body'],
      'for' => [false,'when-body'],
      'foreach' => [false,'when-body'],
      'do' => [false,'when-body'],
      'if' => [false,'when-body'],
      'case' => [false,'when-body'],
      '@' => [false,'when-body'],
      '$' => [false,'when-body'],
      'and' => [false,'when-body'],
      'or' => [false,'when-body'],
    ],
  ],
  'if-block' => [
    0 => [
      'if' => 1,
    ],
    1 => [
      '@' => [2,'value'],
      '$' => [2,'value'],
      '*' => [2,'value'],
      'true' => [2,'value'],
      'false' => [2,'value'],
      '1' => [2,'value'],
      '"' => [2,'value'],
      '\'' => [2,'value'],
      '%' => [2,'value'],
      '[:' => [2,'value'],
      'pure' => [2,'value'],
      'function' => [2,'value'],
      '{' => [2,'value'],
      'and' => [2,'value'],
      'or' => [2,'value'],
    ],
    2 => [
      'then' => 3,
    ],
    3 => [
      'var' => [4,'if-body'],
      'define' => [4,'if-body'],
      'true' => [4,'if-body'],
      'false' => [4,'if-body'],
      '1' => [4,'if-body'],
      '"' => [4,'if-body'],
      '\'' => [4,'if-body'],
      '%' => [4,'if-body'],
      '[:' => [4,'if-body'],
      'pure' => [4,'if-body'],
      'function' => [4,'if-body'],
      '*' => [4,'if-body'],
      '{' => [4,'if-body'],
      'for' => [4,'if-body'],
      'foreach' => [4,'if-body'],
      'do' => [4,'if-body'],
      'if' => [4,'if-body'],
      'case' => [4,'if-body'],
      '@' => [4,'if-body'],
      '$' => [4,'if-body'],
      'and' => [4,'if-body'],
      'or' => [4,'if-body'],
      'exit' => [4,'if-body'],
      'return' => [4,'if-body'],
    ],
    4 => [
      '' => false,
      'else' => [false,'else-case'],
    ],
  ],
  'or-value' => [
    0 => [
      'or' => 1,
    ],
    1 => [
      '(' => 2,
    ],
    2 => [
      '@' => [3,'or-item'],
      '$' => [3,'or-item'],
      '*' => [3,'or-item'],
      'true' => [3,'or-item'],
      'false' => [3,'or-item'],
      '1' => [3,'or-item'],
      '"' => [3,'or-item'],
      '\'' => [3,'or-item'],
      '%' => [3,'or-item'],
      '[:' => [3,'or-item'],
      'pure' => [3,'or-item'],
      'function' => [3,'or-item'],
      '{' => [3,'or-item'],
      'and' => [3,'or-item'],
      'or' => [3,'or-item'],
    ],
    3 => [
      '' => 4,
      ',' => 5,
    ],
    4 => [
      ')' => false,
    ],
    5 => [
      '@' => [3,'or-item'],
      '$' => [3,'or-item'],
      '*' => [3,'or-item'],
      'true' => [3,'or-item'],
      'false' => [3,'or-item'],
      '1' => [3,'or-item'],
      '"' => [3,'or-item'],
      '\'' => [3,'or-item'],
      '%' => [3,'or-item'],
      '[:' => [3,'or-item'],
      'pure' => [3,'or-item'],
      'function' => [3,'or-item'],
      '{' => [3,'or-item'],
      'and' => [3,'or-item'],
      'or' => [3,'or-item'],
    ],
  ],
  'and-value' => [
    0 => [
      'and' => 1,
    ],
    1 => [
      '(' => 2,
    ],
    2 => [
      '@' => [3,'and-item'],
      '$' => [3,'and-item'],
      '*' => [3,'and-item'],
      'true' => [3,'and-item'],
      'false' => [3,'and-item'],
      '1' => [3,'and-item'],
      '"' => [3,'and-item'],
      '\'' => [3,'and-item'],
      '%' => [3,'and-item'],
      '[:' => [3,'and-item'],
      'pure' => [3,'and-item'],
      'function' => [3,'and-item'],
      '{' => [3,'and-item'],
      'and' => [3,'and-item'],
      'or' => [3,'and-item'],
    ],
    3 => [
      '' => 4,
      ',' => 5,
    ],
    4 => [
      ')' => false,
    ],
    5 => [
      '@' => [3,'and-item'],
      '$' => [3,'and-item'],
      '*' => [3,'and-item'],
      'true' => [3,'and-item'],
      'false' => [3,'and-item'],
      '1' => [3,'and-item'],
      '"' => [3,'and-item'],
      '\'' => [3,'and-item'],
      '%' => [3,'and-item'],
      '[:' => [3,'and-item'],
      'pure' => [3,'and-item'],
      'function' => [3,'and-item'],
      '{' => [3,'and-item'],
      'and' => [3,'and-item'],
      'or' => [3,'and-item'],
    ],
  ],
  'list-body' => [
    0 => [
      '' => 1,
      '.' => [1,'list-element'],
      '@' => [1,'list-element'],
      '$' => [1,'list-element'],
      '*' => [1,'list-element'],
      'true' => [1,'list-element'],
      'false' => [1,'list-element'],
      '1' => [1,'list-element'],
      '"' => [1,'list-element'],
      '\'' => [1,'list-element'],
      '%' => [1,'list-element'],
      '[:' => [1,'list-element'],
      'pure' => [1,'list-element'],
      'function' => [1,'list-element'],
      '{' => [1,'list-element'],
      'and' => [1,'list-element'],
      'or' => [1,'list-element'],
    ],
    1 => [
      '' => false,
      ',' => 2,
    ],
    2 => [
      '' => 3,
      ',' => 2,
    ],
    3 => [
      '' => 1,
      '.' => [1,'list-element'],
      '@' => [1,'list-element'],
      '$' => [1,'list-element'],
      '*' => [1,'list-element'],
      'true' => [1,'list-element'],
      'false' => [1,'list-element'],
      '1' => [1,'list-element'],
      '"' => [1,'list-element'],
      '\'' => [1,'list-element'],
      '%' => [1,'list-element'],
      '[:' => [1,'list-element'],
      'pure' => [1,'list-element'],
      'function' => [1,'list-element'],
      '{' => [1,'list-element'],
      'and' => [1,'list-element'],
      'or' => [1,'list-element'],
    ],
  ],
  'case-block' => [
    0 => [
      'case' => 1,
    ],
    1 => [
      '@' => [2,'case-value'],
      '$' => [2,'case-value'],
      '*' => [2,'case-value'],
      'true' => [2,'case-value'],
      'false' => [2,'case-value'],
      '1' => [2,'case-value'],
      '"' => [2,'case-value'],
      '\'' => [2,'case-value'],
      '%' => [2,'case-value'],
      '[:' => [2,'case-value'],
      'pure' => [2,'case-value'],
      'function' => [2,'case-value'],
      '{' => [2,'case-value'],
      'and' => [2,'case-value'],
      'or' => [2,'case-value'],
    ],
    2 => [
      '{' => 3,
    ],
    3 => [
      'when' => [4,'when-case'],
    ],
    4 => [
      '' => 5,
      'when' => [4,'when-case'],
    ],
    5 => [
      '}' => 6,
    ],
    6 => [
      '' => false,
      'else' => [false,'else-case'],
    ],
  ],
  'arg-definition' => [
    0 => [
      '' => 1,
      '@' => 1,
    ],
    1 => [
      '*' => [2,'var-name'],
    ],
    2 => [
      '' => false,
      ':' => 3,
    ],
    3 => [
      '@' => [false,'constant-value'],
      '*' => [false,'constant-value'],
      'true' => [false,'constant-value'],
      'false' => [false,'constant-value'],
      '1' => [false,'constant-value'],
      '"' => [false,'constant-value'],
      '\'' => [false,'constant-value'],
      '%' => [false,'constant-value'],
      '[:' => [false,'constant-value'],
      'pure' => [false,'constant-value'],
      'function' => [false,'constant-value'],
      '{' => [false,'constant-value'],
    ],
  ],
  'variable-spec' => [
    0 => [
      '*' => [1,'var-name'],
    ],
    1 => [
      '' => false,
      ':' => 2,
    ],
    2 => [
      '@' => [false,'constant-value'],
      '*' => [false,'constant-value'],
      'true' => [false,'constant-value'],
      'false' => [false,'constant-value'],
      '1' => [false,'constant-value'],
      '"' => [false,'constant-value'],
      '\'' => [false,'constant-value'],
      '%' => [false,'constant-value'],
      '[:' => [false,'constant-value'],
      'pure' => [false,'constant-value'],
      'function' => [false,'constant-value'],
      '{' => [false,'constant-value'],
    ],
  ],
  'constant' => [
    0 => [
      'define' => 1,
    ],
    1 => [
      '*' => [2,'var-name'],
    ],
    2 => [
      ':' => 3,
    ],
    3 => [
      '@' => [false,'constant-value'],
      '*' => [false,'constant-value'],
      'true' => [false,'constant-value'],
      'false' => [false,'constant-value'],
      '1' => [false,'constant-value'],
      '"' => [false,'constant-value'],
      '\'' => [false,'constant-value'],
      '%' => [false,'constant-value'],
      '[:' => [false,'constant-value'],
      'pure' => [false,'constant-value'],
      'function' => [false,'constant-value'],
      '{' => [false,'constant-value'],
    ],
  ],
  'loop-body' => [
    0 => [
      'var' => [false,'loop-expression'],
      'define' => [false,'loop-expression'],
      'true' => [false,'loop-expression'],
      'false' => [false,'loop-expression'],
      '1' => [false,'loop-expression'],
      '"' => [false,'loop-expression'],
      '\'' => [false,'loop-expression'],
      '%' => [false,'loop-expression'],
      '[:' => [false,'loop-expression'],
      'pure' => [false,'loop-expression'],
      'function' => [false,'loop-expression'],
      '*' => [false,'loop-expression'],
      'for' => [false,'loop-expression'],
      'foreach' => [false,'loop-expression'],
      'do' => [false,'loop-expression'],
      'if' => [false,'loop-expression'],
      'case' => [false,'loop-expression'],
      '@' => [false,'loop-expression'],
      '$' => [false,'loop-expression'],
      'continue' => [false,'loop-expression'],
      'break' => [false,'loop-expression'],
      'while' => [false,'loop-expression'],
      'until' => [false,'loop-expression'],
      '{' => 1,
    ],
    1 => [
      '' => 2,
      'var' => [1,'loop-expression'],
      'define' => [1,'loop-expression'],
      'true' => [1,'loop-expression'],
      'false' => [1,'loop-expression'],
      '1' => [1,'loop-expression'],
      '"' => [1,'loop-expression'],
      '\'' => [1,'loop-expression'],
      '%' => [1,'loop-expression'],
      '[:' => [1,'loop-expression'],
      'pure' => [1,'loop-expression'],
      'function' => [1,'loop-expression'],
      '*' => [1,'loop-expression'],
      'for' => [1,'loop-expression'],
      'foreach' => [1,'loop-expression'],
      'do' => [1,'loop-expression'],
      'if' => [1,'loop-expression'],
      'case' => [1,'loop-expression'],
      '@' => [1,'loop-expression'],
      '$' => [1,'loop-expression'],
      'continue' => [1,'loop-expression'],
      'break' => [1,'loop-expression'],
      'while' => [1,'loop-expression'],
      'until' => [1,'loop-expression'],
    ],
    2 => [
      '}' => false,
    ],
  ],
  'when-body' => [
    0 => [
      'var' => [false,'expression'],
      'define' => [false,'expression'],
      'true' => [false,'expression'],
      'false' => [false,'expression'],
      '1' => [false,'expression'],
      '"' => [false,'expression'],
      '\'' => [false,'expression'],
      '%' => [false,'expression'],
      '[:' => [false,'expression'],
      'pure' => [false,'expression'],
      'function' => [false,'expression'],
      '*' => [false,'expression'],
      '{' => [false,'expression'],
      'for' => [false,'expression'],
      'foreach' => [false,'expression'],
      'do' => [false,'expression'],
      'if' => [false,'expression'],
      'case' => [false,'expression'],
      '@' => [false,'expression'],
      '$' => [false,'expression'],
      'and' => [false,'expression'],
      'or' => [false,'expression'],
    ],
  ],
  'else-case' => [
    0 => [
      'else' => 1,
    ],
    1 => [
      'var' => [false,'expression'],
      'define' => [false,'expression'],
      'true' => [false,'expression'],
      'false' => [false,'expression'],
      '1' => [false,'expression'],
      '"' => [false,'expression'],
      '\'' => [false,'expression'],
      '%' => [false,'expression'],
      '[:' => [false,'expression'],
      'pure' => [false,'expression'],
      'function' => [false,'expression'],
      '*' => [false,'expression'],
      '{' => [false,'expression'],
      'for' => [false,'expression'],
      'foreach' => [false,'expression'],
      'do' => [false,'expression'],
      'if' => [false,'expression'],
      'case' => [false,'expression'],
      '@' => [false,'expression'],
      '$' => [false,'expression'],
      'and' => [false,'expression'],
      'or' => [false,'expression'],
      'exit' => [false,'flow-control'],
      'return' => [false,'flow-control'],
    ],
  ],
  'if-body' => [
    0 => [
      'var' => [false,'expression'],
      'define' => [false,'expression'],
      'true' => [false,'expression'],
      'false' => [false,'expression'],
      '1' => [false,'expression'],
      '"' => [false,'expression'],
      '\'' => [false,'expression'],
      '%' => [false,'expression'],
      '[:' => [false,'expression'],
      'pure' => [false,'expression'],
      'function' => [false,'expression'],
      '*' => [false,'expression'],
      '{' => [false,'expression'],
      'for' => [false,'expression'],
      'foreach' => [false,'expression'],
      'do' => [false,'expression'],
      'if' => [false,'expression'],
      'case' => [false,'expression'],
      '@' => [false,'expression'],
      '$' => [false,'expression'],
      'and' => [false,'expression'],
      'or' => [false,'expression'],
      'exit' => [false,'flow-control'],
      'return' => [false,'flow-control'],
    ],
  ],
  'compound-value' => [
    0 => [
      '{' => 1,
    ],
    1 => [
      '' => 2,
      'var' => [1,'expression'],
      'define' => [1,'expression'],
      'true' => [1,'expression'],
      'false' => [1,'expression'],
      '1' => [1,'expression'],
      '"' => [1,'expression'],
      '\'' => [1,'expression'],
      '%' => [1,'expression'],
      '[:' => [1,'expression'],
      'pure' => [1,'expression'],
      'function' => [1,'expression'],
      '*' => [1,'expression'],
      '{' => [1,'expression'],
      'for' => [1,'expression'],
      'foreach' => [1,'expression'],
      'do' => [1,'expression'],
      'if' => [1,'expression'],
      'case' => [1,'expression'],
      '@' => [1,'expression'],
      '$' => [1,'expression'],
      'and' => [1,'expression'],
      'or' => [1,'expression'],
    ],
    2 => [
      '}' => false,
    ],
  ],
  'meta' => [
    0 => [
      '\\{' => 1,
    ],
    1 => [
      '' => 2,
      'var' => [1,'expression'],
      'define' => [1,'expression'],
      'true' => [1,'expression'],
      'false' => [1,'expression'],
      '1' => [1,'expression'],
      '"' => [1,'expression'],
      '\'' => [1,'expression'],
      '%' => [1,'expression'],
      '[:' => [1,'expression'],
      'pure' => [1,'expression'],
      'function' => [1,'expression'],
      '*' => [1,'expression'],
      '{' => [1,'expression'],
      'for' => [1,'expression'],
      'foreach' => [1,'expression'],
      'do' => [1,'expression'],
      'if' => [1,'expression'],
      'case' => [1,'expression'],
      '@' => [1,'expression'],
      '$' => [1,'expression'],
      'and' => [1,'expression'],
      'or' => [1,'expression'],
      '\\{' => [1,'meta'],
    ],
    2 => [
      '}\\' => false,
    ],
  ],
  'or-item' => [
    0 => [
      '@' => [false,'value'],
      '$' => [false,'value'],
      '*' => [false,'value'],
      'true' => [false,'value'],
      'false' => [false,'value'],
      '1' => [false,'value'],
      '"' => [false,'value'],
      '\'' => [false,'value'],
      '%' => [false,'value'],
      '[:' => [false,'value'],
      'pure' => [false,'value'],
      'function' => [false,'value'],
      '{' => [false,'value'],
      'and' => [false,'value'],
      'or' => [false,'value'],
    ],
  ],
  'and-item' => [
    0 => [
      '@' => [false,'value'],
      '$' => [false,'value'],
      '*' => [false,'value'],
      'true' => [false,'value'],
      'false' => [false,'value'],
      '1' => [false,'value'],
      '"' => [false,'value'],
      '\'' => [false,'value'],
      '%' => [false,'value'],
      '[:' => [false,'value'],
      'pure' => [false,'value'],
      'function' => [false,'value'],
      '{' => [false,'value'],
      'and' => [false,'value'],
      'or' => [false,'value'],
    ],
  ],
  'pair' => [
    0 => [
      '.' => 1,
    ],
    1 => [
      '*' => [2,'key'],
      '"' => [2,'string'],
      '\'' => [2,'string'],
      '%' => [2,'string'],
      '{' => [2,'compound-value'],
    ],
    2 => [
      ':' => 3,
    ],
    3 => [
      '@' => [false,'value'],
      '$' => [false,'value'],
      '*' => [false,'value'],
      'true' => [false,'value'],
      'false' => [false,'value'],
      '1' => [false,'value'],
      '"' => [false,'value'],
      '\'' => [false,'value'],
      '%' => [false,'value'],
      '[:' => [false,'value'],
      'pure' => [false,'value'],
      'function' => [false,'value'],
      '{' => [false,'value'],
      'and' => [false,'value'],
      'or' => [false,'value'],
    ],
  ],
  'deref' => [
    0 => [
      '$' => 1,
    ],
    1 => [
      '@' => [false,'value'],
      '$' => [false,'value'],
      '*' => [false,'value'],
      'true' => [false,'value'],
      'false' => [false,'value'],
      '1' => [false,'value'],
      '"' => [false,'value'],
      '\'' => [false,'value'],
      '%' => [false,'value'],
      '[:' => [false,'value'],
      'pure' => [false,'value'],
      'function' => [false,'value'],
      '{' => [false,'value'],
      'and' => [false,'value'],
      'or' => [false,'value'],
    ],
  ],
  'reference' => [
    0 => [
      '@' => 1,
    ],
    1 => [
      '@' => [false,'value'],
      '$' => [false,'value'],
      '*' => [false,'value'],
      'true' => [false,'value'],
      'false' => [false,'value'],
      '1' => [false,'value'],
      '"' => [false,'value'],
      '\'' => [false,'value'],
      '%' => [false,'value'],
      '[:' => [false,'value'],
      'pure' => [false,'value'],
      'function' => [false,'value'],
      '{' => [false,'value'],
      'and' => [false,'value'],
      'or' => [false,'value'],
    ],
  ],
  'loop-control' => [
    0 => [
      'continue' => false,
      'break' => false,
      'while' => 1,
      'until' => 2,
    ],
    1 => [
      '@' => [false,'value'],
      '$' => [false,'value'],
      '*' => [false,'value'],
      'true' => [false,'value'],
      'false' => [false,'value'],
      '1' => [false,'value'],
      '"' => [false,'value'],
      '\'' => [false,'value'],
      '%' => [false,'value'],
      '[:' => [false,'value'],
      'pure' => [false,'value'],
      'function' => [false,'value'],
      '{' => [false,'value'],
      'and' => [false,'value'],
      'or' => [false,'value'],
    ],
    2 => [
      '@' => [false,'value'],
      '$' => [false,'value'],
      '*' => [false,'value'],
      'true' => [false,'value'],
      'false' => [false,'value'],
      '1' => [false,'value'],
      '"' => [false,'value'],
      '\'' => [false,'value'],
      '%' => [false,'value'],
      '[:' => [false,'value'],
      'pure' => [false,'value'],
      'function' => [false,'value'],
      '{' => [false,'value'],
      'and' => [false,'value'],
      'or' => [false,'value'],
    ],
  ],
  'loop-case-block' => [
    0 => [
      'case' => 1,
    ],
    1 => [
      '@' => [2,'value'],
      '$' => [2,'value'],
      '*' => [2,'value'],
      'true' => [2,'value'],
      'false' => [2,'value'],
      '1' => [2,'value'],
      '"' => [2,'value'],
      '\'' => [2,'value'],
      '%' => [2,'value'],
      '[:' => [2,'value'],
      'pure' => [2,'value'],
      'function' => [2,'value'],
      '{' => [2,'value'],
      'and' => [2,'value'],
      'or' => [2,'value'],
    ],
    2 => [
      '{' => 3,
    ],
    3 => [
      'when' => [4,'when-case'],
    ],
    4 => [
      '' => 5,
      'when' => [4,'when-case'],
    ],
    5 => [
      '}' => 6,
    ],
    6 => [
      '' => false,
      'else' => [false,'loop-else-case'],
    ],
  ],
  'list-element' => [
    0 => [
      '.' => [false,'pair'],
      '@' => [false,'value'],
      '$' => [false,'value'],
      '*' => [false,'value'],
      'true' => [false,'value'],
      'false' => [false,'value'],
      '1' => [false,'value'],
      '"' => [false,'value'],
      '\'' => [false,'value'],
      '%' => [false,'value'],
      '[:' => [false,'value'],
      'pure' => [false,'value'],
      'function' => [false,'value'],
      '{' => [false,'value'],
      'and' => [false,'value'],
      'or' => [false,'value'],
    ],
  ],
  'when-value' => [
    0 => [
      '@' => [false,'value'],
      '$' => [false,'value'],
      '*' => [false,'value'],
      'true' => [false,'value'],
      'false' => [false,'value'],
      '1' => [false,'value'],
      '"' => [false,'value'],
      '\'' => [false,'value'],
      '%' => [false,'value'],
      '[:' => [false,'value'],
      'pure' => [false,'value'],
      'function' => [false,'value'],
      '{' => [false,'value'],
      'and' => [false,'value'],
      'or' => [false,'value'],
    ],
  ],
  'case-value' => [
    0 => [
      '@' => [false,'value'],
      '$' => [false,'value'],
      '*' => [false,'value'],
      'true' => [false,'value'],
      'false' => [false,'value'],
      '1' => [false,'value'],
      '"' => [false,'value'],
      '\'' => [false,'value'],
      '%' => [false,'value'],
      '[:' => [false,'value'],
      'pure' => [false,'value'],
      'function' => [false,'value'],
      '{' => [false,'value'],
      'and' => [false,'value'],
      'or' => [false,'value'],
    ],
  ],
  'each-object' => [
    0 => [
      '@' => [false,'value'],
      '$' => [false,'value'],
      '*' => [false,'value'],
      'true' => [false,'value'],
      'false' => [false,'value'],
      '1' => [false,'value'],
      '"' => [false,'value'],
      '\'' => [false,'value'],
      '%' => [false,'value'],
      '[:' => [false,'value'],
      'pure' => [false,'value'],
      'function' => [false,'value'],
      '{' => [false,'value'],
      'and' => [false,'value'],
      'or' => [false,'value'],
    ],
  ],
  'concat' => [
    0 => [
      '::' => 1,
    ],
    1 => [
      '@' => [false,'value'],
      '$' => [false,'value'],
      '*' => [false,'value'],
      'true' => [false,'value'],
      'false' => [false,'value'],
      '1' => [false,'value'],
      '"' => [false,'value'],
      '\'' => [false,'value'],
      '%' => [false,'value'],
      '[:' => [false,'value'],
      'pure' => [false,'value'],
      'function' => [false,'value'],
      '{' => [false,'value'],
      'and' => [false,'value'],
      'or' => [false,'value'],
    ],
  ],
  'set' => [
    0 => [
      ':' => 1,
    ],
    1 => [
      '@' => [false,'value'],
      '$' => [false,'value'],
      '*' => [false,'value'],
      'true' => [false,'value'],
      'false' => [false,'value'],
      '1' => [false,'value'],
      '"' => [false,'value'],
      '\'' => [false,'value'],
      '%' => [false,'value'],
      '[:' => [false,'value'],
      'pure' => [false,'value'],
      'function' => [false,'value'],
      '{' => [false,'value'],
      'and' => [false,'value'],
      'or' => [false,'value'],
    ],
  ],
  'flow-control' => [
    0 => [
      'exit' => false,
      'return' => 1,
    ],
    1 => [
      '@' => [false,'value'],
      '$' => [false,'value'],
      '*' => [false,'value'],
      'true' => [false,'value'],
      'false' => [false,'value'],
      '1' => [false,'value'],
      '"' => [false,'value'],
      '\'' => [false,'value'],
      '%' => [false,'value'],
      '[:' => [false,'value'],
      'pure' => [false,'value'],
      'function' => [false,'value'],
      '{' => [false,'value'],
      'and' => [false,'value'],
      'or' => [false,'value'],
    ],
  ],
  'constant-value' => [
    0 => [
      '@' => [false,'const-object'],
      '*' => [false,'const-object'],
      'true' => [false,'const-object'],
      'false' => [false,'const-object'],
      '1' => [false,'const-object'],
      '"' => [false,'const-object'],
      '\'' => [false,'const-object'],
      '%' => [false,'const-object'],
      '[:' => [false,'const-object'],
      'pure' => [false,'const-object'],
      'function' => [false,'const-object'],
      '{' => [false,'const-compound'],
    ],
  ],
  'item' => [
    0 => [
      '[' => 1,
    ],
    1 => [
      '{' => [2,'item-value'],
      '*' => [2,'item-value'],
      'true' => [2,'item-value'],
      'false' => [2,'item-value'],
      '1' => [2,'item-value'],
      '"' => [2,'item-value'],
      '\'' => [2,'item-value'],
      '%' => [2,'item-value'],
      '[:' => [2,'item-value'],
      'pure' => [2,'item-value'],
      'function' => [2,'item-value'],
    ],
    2 => [
      '' => 3,
      ',' => 4,
    ],
    3 => [
      ']' => false,
    ],
    4 => [
      '{' => [2,'item-value'],
      '*' => [2,'item-value'],
      'true' => [2,'item-value'],
      'false' => [2,'item-value'],
      '1' => [2,'item-value'],
      '"' => [2,'item-value'],
      '\'' => [2,'item-value'],
      '%' => [2,'item-value'],
      '[:' => [2,'item-value'],
      'pure' => [2,'item-value'],
      'function' => [2,'item-value'],
    ],
  ],
  'loop-expression' => [
    0 => [
      'var' => [false,'definition'],
      'define' => [false,'definition'],
      'true' => [false,'literal-expression'],
      'false' => [false,'literal-expression'],
      '1' => [false,'literal-expression'],
      '"' => [false,'literal-expression'],
      '\'' => [false,'literal-expression'],
      '%' => [false,'literal-expression'],
      '[:' => [false,'literal-expression'],
      'pure' => [false,'literal-expression'],
      'function' => [false,'literal-expression'],
      '*' => [false,'object-expression'],
      'for' => [false,'block-expression'],
      'foreach' => [false,'block-expression'],
      'do' => [false,'block-expression'],
      'if' => [false,'loop-if-block'],
      'case' => [false,'loop-case-block'],
      '@' => [false,'reference-expression'],
      '$' => [false,'deref-expression'],
      'continue' => [false,'loop-control'],
      'break' => [false,'loop-control'],
      'while' => [false,'loop-control'],
      'until' => [false,'loop-control'],
    ],
  ],
  'expression' => [
    0 => [
      'var' => [false,'definition'],
      'define' => [false,'definition'],
      'true' => [false,'literal-expression'],
      'false' => [false,'literal-expression'],
      '1' => [false,'literal-expression'],
      '"' => [false,'literal-expression'],
      '\'' => [false,'literal-expression'],
      '%' => [false,'literal-expression'],
      '[:' => [false,'literal-expression'],
      'pure' => [false,'literal-expression'],
      'function' => [false,'literal-expression'],
      '*' => [false,'object-expression'],
      '{' => [false,'compound-expression'],
      'for' => [false,'block-expression'],
      'foreach' => [false,'block-expression'],
      'do' => [false,'block-expression'],
      'if' => [false,'if-block'],
      'case' => [false,'case-block'],
      '@' => [false,'reference-expression'],
      '$' => [false,'deref-expression'],
      'and' => [false,'logic-expression'],
      'or' => [false,'logic-expression'],
    ],
  ],
  'value' => [
    0 => [
      '@' => [false,'reference'],
      '$' => [false,'deref'],
      '*' => [false,'object'],
      'true' => [false,'literal-object'],
      'false' => [false,'literal-object'],
      '1' => [false,'literal-object'],
      '"' => [false,'literal-object'],
      '\'' => [false,'literal-object'],
      '%' => [false,'literal-object'],
      '[:' => [false,'literal-object'],
      'pure' => [false,'literal-object'],
      'function' => [false,'literal-object'],
      '{' => [false,'compound-value'],
      'and' => [false,'logic-value'],
      'or' => [false,'logic-value'],
    ],
  ],
  'const-object' => [
    0 => [
      '' => 1,
      '@' => 1,
    ],
    1 => [
      '*' => [false,'object'],
      'true' => [false,'literal-object'],
      'false' => [false,'literal-object'],
      '1' => [false,'literal-object'],
      '"' => [false,'literal-object'],
      '\'' => [false,'literal-object'],
      '%' => [false,'literal-object'],
      '[:' => [false,'literal-object'],
      'pure' => [false,'literal-object'],
      'function' => [false,'literal-object'],
    ],
  ],
  'item-value' => [
    0 => [
      '{' => [false,'compound-value'],
      '*' => [false,'object'],
      'true' => [false,'literal-object'],
      'false' => [false,'literal-object'],
      '1' => [false,'literal-object'],
      '"' => [false,'literal-object'],
      '\'' => [false,'literal-object'],
      '%' => [false,'literal-object'],
      '[:' => [false,'literal-object'],
      'pure' => [false,'literal-object'],
      'function' => [false,'literal-object'],
    ],
  ],
  'for-step' => [
    0 => [
      '*' => [false,'object'],
      'true' => [false,'literal-object'],
      'false' => [false,'literal-object'],
      '1' => [false,'literal-object'],
      '"' => [false,'literal-object'],
      '\'' => [false,'literal-object'],
      '%' => [false,'literal-object'],
      '[:' => [false,'literal-object'],
      'pure' => [false,'literal-object'],
      'function' => [false,'literal-object'],
      '{' => [false,'compound-value'],
    ],
  ],
  'for-end' => [
    0 => [
      '*' => [false,'object'],
      'true' => [false,'literal-object'],
      'false' => [false,'literal-object'],
      '1' => [false,'literal-object'],
      '"' => [false,'literal-object'],
      '\'' => [false,'literal-object'],
      '%' => [false,'literal-object'],
      '[:' => [false,'literal-object'],
      'pure' => [false,'literal-object'],
      'function' => [false,'literal-object'],
      '{' => [false,'compound-value'],
    ],
  ],
  'for-start' => [
    0 => [
      '*' => [false,'object'],
      'true' => [false,'literal-object'],
      'false' => [false,'literal-object'],
      '1' => [false,'literal-object'],
      '"' => [false,'literal-object'],
      '\'' => [false,'literal-object'],
      '%' => [false,'literal-object'],
      '[:' => [false,'literal-object'],
      'pure' => [false,'literal-object'],
      'function' => [false,'literal-object'],
      '{' => [false,'compound-value'],
    ],
  ],
  'literal-expression' => [
    0 => [
      'true' => [false,'literal-object'],
      'false' => [false,'literal-object'],
      '1' => [false,'literal-object'],
      '"' => [false,'literal-object'],
      '\'' => [false,'literal-object'],
      '%' => [false,'literal-object'],
      '[:' => [false,'literal-object'],
      'pure' => [false,'literal-object'],
      'function' => [false,'literal-object'],
    ],
  ],
  'logic-expression' => [
    0 => [
      'and' => [false,'logic-value'],
      'or' => [false,'logic-value'],
    ],
  ],
  'literal-object' => [
    0 => [
      'true' => [1,'literal'],
      'false' => [1,'literal'],
      '1' => [1,'literal'],
      '"' => [1,'literal'],
      '\'' => [1,'literal'],
      '%' => [1,'literal'],
      '[:' => [1,'literal'],
      'pure' => [1,'literal'],
      'function' => [1,'literal'],
    ],
    1 => [
      '' => false,
      '(' => [1,'call'],
      '[' => [1,'item'],
      '.' => [1,'field'],
    ],
  ],
  'object-expression' => [
    0 => [
      '*' => [1,'object'],
    ],
    1 => [
      '' => false,
      ':' => [false,'operation'],
      '::' => [false,'operation'],
    ],
  ],
  'each-index' => [
    0 => [
      '*' => [false,'object'],
    ],
  ],
  'each-key' => [
    0 => [
      '*' => [false,'object'],
    ],
  ],
  'each-value' => [
    0 => [
      '*' => [false,'object'],
    ],
  ],
  'for-counter' => [
    0 => [
      '*' => [false,'object'],
    ],
  ],
  'logic-value' => [
    0 => [
      'and' => [false,'and-value'],
      'or' => [false,'or-value'],
    ],
  ],
  'var-name' => [
    0 => [
      '*' => false,
    ],
  ],
  'const-compound' => [
    0 => [
      '{' => [false,'compound-value'],
    ],
  ],
  'string' => [
    0 => [
      '"' => false,
      '\'' => false,
      '%' => false,
    ],
  ],
  'number' => [
    0 => [
      '1' => false,
    ],
  ],
  'bool' => [
    0 => [
      'true' => false,
      'false' => false,
    ],
  ],
  'key' => [
    0 => [
      '*' => false,
    ],
  ],
  'name' => [
    0 => [
      '*' => false,
    ],
  ],
  'field' => [
    0 => [
      '.' => 1,
    ],
    1 => [
      '*' => [false,'key'],
    ],
  ],
  'literal' => [
    0 => [
      'true' => [false,'bool'],
      'false' => [false,'bool'],
      '1' => [false,'number'],
      '"' => [false,'string'],
      '\'' => [false,'string'],
      '%' => [false,'string'],
      '[:' => [false,'list'],
      'pure' => [false,'function'],
      'function' => [false,'function'],
    ],
  ],
  'operation' => [
    0 => [
      ':' => [false,'set'],
      '::' => [false,'concat'],
    ],
  ],
  'object' => [
    0 => [
      '*' => [1,'name'],
    ],
    1 => [
      '' => false,
      '(' => [1,'call'],
      '[' => [1,'item'],
      '.' => [1,'field'],
    ],
  ],
  'deref-expression' => [
    0 => [
      '$' => [false,'deref'],
    ],
  ],
  'reference-expression' => [
    0 => [
      '@' => [false,'reference'],
    ],
  ],
  'block-expression' => [
    0 => [
      'for' => [false,'for-block'],
      'foreach' => [false,'foreach-block'],
      'do' => [false,'do-block'],
    ],
  ],
  'compound-expression' => [
    0 => [
      '{' => [false,'compound-value'],
    ],
  ],
  'definition' => [
    0 => [
      'var' => [false,'variable'],
      'define' => [false,'constant'],
    ],
  ],
];

